# -----------------------
# 1. Base de donn\u00E9es
# -----------------------
spring.datasource.url=jdbc:mysql://localhost:3306/stock_db1?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Supprimer cette ligne si tu ne veux pas utiliser schema.sql
# spring.datasource.initialization-mode=always
# spring.datasource.platform=mysql

# Pour afficher les requ\u00EAtes SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Cr\u00E9ation / mise \u00E0 jour automatique du sch\u00E9ma
spring.jpa.hibernate.ddl-auto=update

# Dialecte SQL adapt\u00E9 \u00E0 MySQL 8
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# -----------------------
# 2. Serveur Web
# -----------------------
server.port=8080

# -----------------------
# 3. Localisation / Fuseau horaire
# -----------------------
spring.jackson.time-zone=Africa/Ouagadougou
spring.main.allow-bean-definition-overriding=true
debug=true
spring.web.resources.static-locations=classpath:/static/,file:uploads/
