# -----------------------
# 1. Base de données
# -----------------------
spring.datasource.url=jdbc:mysql://localhost:3306/stock_db1?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Mode d'initialisation (execute schema.sql + data.sql)
spring.datasource.initialization-mode=always
spring.datasource.platform=mysql

# Pour afficher les requêtes SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Création / mise à jour automatique du schéma (optionnel)
# On laisse schema.sql faire le job, donc on commente cette ligne
# spring.jpa.hibernate.ddl-auto=none

# Facultatif : paramètre de validation
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# -----------------------
# 2. Serveur Web
# -----------------------
server.port=3306

# -----------------------
# 3. Localisation / Fuseau horaire
# -----------------------
spring.jackson.time-zone=Africa/Ouagadougou
spring.main.allow-bean-definition-overriding=true
debug=true